### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by ghost** [hirayaku/DAC2018-TGIIF#7]
Hi,

  Great repo and congratulate! 
  I have installed the DNNDK and finish the guide of  compression and compilation. 
  
1. I'm wonder which version of caffe you used to build your own ssd model? 

2. And how can I train to get the float model? Can you provide the float.prototxt and the version of caffe?

Thanks

**Comment by WeicongChen** [comment]
Hi, the training files are uploaded [here](https://github.com/hirayaku/DAC2018-TGIIF/tree/master/train).  Noting that we use the fixed-point instead of the float-point for data representation during training, we only provide the prototxts with fixed-point layers. You can replace those layers with float-point ones and then train the network using [Caffe-SSD](https://github.com/weiliu89/caffe/tree/ssd).

**Comment by shinya321** [comment]
Dear   juicecwc,
Thank u very much for your uploading script for training! I am really interested in it.
As you already mentioned in "train" folder, I realize that at first I need to train by executing solver.prototxt with my own dataset on caffe environment.
But I am not sure after that. After training and getting an original ".caffemodel", how can I implement it to execute ur SSD??
I guess it's impossible to change DPU RTL IP of DeePhi, but possible to update original parameter created by my own training on the same IP.

it would be greatly appreciated if you could explain the details.
Best regards,
shinya321

**Comment by sl-zeng** [comment]
Hi shinya321,

Yes, it is okay to updata the parameter of the SSD. In order to do that, you need to download the DNNDK package from [http://www.deephi.com/technology/dnndk](http://www.deephi.com/technology/dnndk).

You should use DECENT tool for network compression and quantization, then DNNC for compilation.
Please follow the instructions in the DeePhi DNNDK user guide.

If you have any further questions, please let us know.

Best Regards,
sl-zeng
